# This is a basic workflow to help you get started with Actions

name: CI-SEAWEEDFS_GATEWAY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-liveness-check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-openresty@v1
        with:
          openrestyVersion: "1.21.4.2"
      - shell: bash
        run: echo -e 'github_account=cooperlyt\ngithub_token=${{ secrets.OPM_GITHUB_TOKEN }}\nupload_server=https://opm.openresty.org\ndownload_server=https://opm.openresty.org' > ~/.opmrc && cd /tmp && opm build && opm upload
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: coopersoft
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2          
      - shell: bash
        run: cd demo && ./docker_build.sh


